---

#
# Nodemanager systemd
#

- name: Copy Nodemanager Properties file
  template: src=nodemanager.properties.j2 dest={{ nodemanager_home }}/nodemanager.properties
      
- name: Copy nodemanager systemd script
  template: src=nodemanager.service.j2 dest=/etc/systemd/system/nodemanager.service mode=0755
  become_user: root

- name: Enable nodemanager as linux service
  command: 'systemctl enable nodemanager'
  become_user: root

- name: Start Node Manager
  command: 'systemctl start nodemanager'
  become_user: root

- name: Waiting for nodemanager to come up
  wait_for: host="{{ ansible_fqdn }}" port=5556 delay=2 timeout=300
  become_user: root
            
